global:
  scrape_interval: 5s
  external_labels:
    monitor: 'prometheus'
scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
    - targets: ['webapi-otel-collector:8889']
    - targets: ['grpcservice-otel-collector:8890']